language: python
sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.7-dev

install:
  - python setup.py install
  - pip install -r requirements-dev.txt
  - pip install codecov

script:
  - make cov

after_success:
  - codecov
